---
 - hosts: jenkins-server
   become: true
   name: Installing Java and Jenkins on jenkins-server
   tasks:
     - name: Installing Java
       ansible.builtin.apt: 
         name: openjdk-8-jdk
         state: latest
         install_recommends: yes
     - name: Installing Jenkins Via Script
       ansible.builtin.copy:
         name: Copying the jenkins-script to the remote server
         src: ansible/jenkins-install.sh
         dest: /tmp/jenkins
         mode: 0777
       ansible.builtin.command:
         name: Executing jenkins-script to the remote server
         cmd: /bin/sh /tmp/jenkins/jenkins-install.sh
       ansible.builtin.service:
         name: jenkins
         enable: yes
         state: started
         


