---
- hosts: jenkins-master
  become: true
  name: Installing Java and Jenkins on jenkins-server
  tasks:

    - name: Installing Java
      ansible.builtin.apt:
        name: openjdk-8-jdk
        state: latest
        install_recommends: yes

    - name: Copying the jenkins-script to the remote server
      ansible.builtin.copy:
        name: Copying the script
        src: ansible/jenkins-install.sh
        dest: /tmp/jenkins
        mode: 0777
    
    - name: Executing jenkins-script to the remote server
      ansible.builtin.command:
        name: Executing script
        cmd: /bin/sh /tmp/jenkins/jenkins-install.sh

    - name: Enabling jenkins service
      ansible.builtin.service:
        name: jenkins
        enable: yes
        state: started
