FROM maven:3.8.4-jdk-11
COPY . /usr/src/selenium-test
WORKDIR /usr/src/selenium-test
RUN chmod +x driver/chromedriver
RUN mvn clean package
RUN mvn clean compile assembly:single
RUN java -jar target/Selenium-1.0-SNAPSHOT-jar-with-dependencies.jar